server:
  port: 8082  # 端口号

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cbz_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml